In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1.2,3,4),(4,3,2)], dtype = float)
c=np.array([[(1,2),(3,4)],[(3,2),(4,5)]])
c

array([[[1, 2],
        [3, 4]],

       [[3, 2],
        [4, 5]]])

In [15]:
import numpy as np
array=np.zeros((3,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
arr=np.ones((2,3,4)) #2layers, 3 rows, 4 cols
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
d=np.arange(10,2,25)
d

array([], dtype=int32)

In [20]:
dee=np.linspace(0,2,9)
dee

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
e=np.full((2,4),7)
print(e)

[[7 7 7 7]
 [7 7 7 7]]


In [25]:
f=np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [29]:
x=np.random.random((2,4,3))
print(x)

[[[0.85413661 0.07870744 0.46956704]
  [0.89484404 0.98288208 0.81701982]
  [0.59470814 0.47840435 0.41619649]
  [0.02114787 0.6329577  0.89620768]]

 [[0.74277693 0.00853812 0.78246359]
  [0.12532723 0.64411274 0.74776054]
  [0.25121391 0.59834856 0.64716151]
  [0.84102495 0.87848219 0.51598824]]]


In [34]:
arr5=np.empty((4,5))
arr5

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78020984e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 2.78149851e-307, 1.06811422e-306,
        8.45590539e-307, 6.23054972e-307],
       [9.34609790e-307, 1.78019354e-306, 1.69119330e-306,
        1.24611470e-306, 2.56765117e-312]])

In [39]:
arr=np.array([1,2,3,4,5])
np.save('my_array.npy', arr)

In [40]:
loaded_arr = np.load('my_array.npy')

print(loaded_arr)

[1 2 3 4 5]


In [41]:
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
arr3=np.array([4,3,2])

np.savez('myyy_array.npz',array1=arr1,array2=arr2,array3=arr3)

In [42]:
loaded_data = np.load('myyy_array.npz')

loaded_arr1 = loaded_data['array1']
loaded_arr2 = loaded_data['array2']
loaded_arr3 = loaded_data['array3']

print(loaded_arr1)
print(loaded_arr2)
print(loaded_arr3)

[1 2 3]
[3 4 5]
[4 3 2]


In [11]:
import numpy as np
data = np.loadtxt("myfile")
print(data)

ValueError: could not convert string '1,2,' to float64 at row 0, column 1.

In [10]:
dataa = np.genfromtxt("myfile", delimiter=',')
print(dataa)

[1. 2. 3. 4. 5.]


In [20]:
a=np.array([(1,2,3),(3,4,5)],dtype=int)
dat=np.savetxt("myfile",a,delimiter=" ",fmt='%d')
print(type(a))


<class 'numpy.ndarray'>


In [21]:
print(a)

[[1 2 3]
 [3 4 5]]


In [23]:
b=np.array([(1,1,1),(2,2,2)])
print(b)

[[1 1 1]
 [2 2 2]]


In [25]:
g=a-b
print(g)

[[0 1 2]
 [1 2 3]]


In [26]:
f=np.subtract(a,b)
print(f)

[[0 1 2]
 [1 2 3]]


In [28]:
c=np.array([(1,1),(2,2),(3,3)])
print(c)

[[1 1]
 [2 2]
 [3 3]]


In [29]:
l=c.dot(b)
print(l)

[[3 3 3]
 [6 6 6]
 [9 9 9]]


In [30]:
v=np.log(16)
print(v)

2.772588722239781


In [32]:
k=np.sin(60)
print(k)

-0.3048106211022167


In [33]:
degree= 60
radians = np.radians(degree)

sin_value = np.sin(radians)
print(f"{sin_value}")

0.8660254037844386


In [34]:
a == b

array([[ True, False, False],
       [False, False, False]])

In [38]:
c>2

array([[False, False],
       [False, False],
       [ True,  True]])

In [39]:
a.sum()

18

In [45]:
print(a)
print("-----")
print(b)
print("-----")
print(c)

[[1 2 3]
 [3 4 5]]
-----
[[1 1 1]
 [2 2 2]]
-----
[[1 1]
 [2 2]
 [3 3]]


In [42]:
a.min()

1

In [52]:
x=np.max(a,axis=1)[0]
print(x)

3


In [53]:
er=np.mean(a)
print(er)

3.0


In [54]:
ere=np.median(c)
print(ere)

2.0


In [56]:
ds=np.corrcoef(a)
print(ds)

[[1. 1.]
 [1. 1.]]


In [58]:
xs=np.std(a)
print(xs)

1.2909944487358056


In [61]:
dse = a.view()
print(dse)

[[1 2 3]
 [3 4 5]]


In [62]:
ss=np.copy(a)
print(ss)

[[1 2 3]
 [3 4 5]]


In [64]:
ll=a.copy()
print(ll)

[[1 2 3]
 [3 4 5]]


In [70]:
arr5 = np.array([1,34,223,65,75,23,33,2])
arr5.sort()
print(arr5)

[  1   2  23  33  34  65  75 223]


In [79]:
raa = np.array([(43,62,200),(45,65,32)])
raa.sort(axis=0)
print(raa)

[[ 43  62  32]
 [ 45  65 200]]


In [80]:
print(a)
print(b)
print(c)

[[1 2 3]
 [3 4 5]]
[[1 1 1]
 [2 2 2]]
[[1 1]
 [2 2]
 [3 3]]


In [82]:
i=np.transpose(b)
print(i)

[[1 2]
 [1 2]
 [1 2]]


In [83]:
i.T

array([[1, 1, 1],
       [2, 2, 2]])

In [87]:
d=a.ravel()
print(d)

[1 2 3 3 4 5]


In [88]:
hh=b.reshape(3,-1)
print(hh)

[[1 1]
 [1 2]
 [2 2]]


In [92]:
hh.resize((2,6))


ValueError: cannot resize this array: it does not own its data