<a href="https://colab.research.google.com/github/Tejaswi408/Repo-ML/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape) #size along the dimension
print(arr.ndim) #since array is one dimensional array

[1 2 3 4 5]
(5,)
1


In [ ]:
print(type(arr)) #arr is an instance of the ndarray class

<class 'numpy.ndarray'>


In [ ]:
#zeroD Array
arr1=np.array(45)
print(arr1.shape)
print(arr1.ndim)
print(type(arr1))

()
0
<class 'numpy.ndarray'>


In [ ]:
#2D Array
import numpy as np
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
(2, 3)
2
<class 'numpy.ndarray'>


In [ ]:
#3d array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [ ]:
#creating n dimensional array
arr4 = np.array([1,2,3,4,5], ndmin = 5)
print(arr4)
print(arr4.shape)
print(arr4.ndim)


[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
5


In [ ]:
#slicing arrays
print(arr1, arr[0],arr2[0, 1], arr3[0,1,2])


45 1 hel 2 6


In [ ]:
print(arr2)
print(arr2[-2,- 1])

[[1 2 3]
 [4 5 6]]
3


In [ ]:
arr4 = np.array([1,2,3,4,5,6,7])

print(arr4[1:5])
print(arr4[-5:-1])
print(arr4[2:])
print(arr4[:4])
print(arr4[0:7:2])
print(arr4[::2])


[2 3 4 5]
[3 4 5 6]
[3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]
[1 3 5 7]


In [ ]:
arr5 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr5
print(arr5[1, 1:4])
print(arr5[0:2, 2])
print(arr5[0:2, 1:4])


[6 7 8]
[3 7]
[[2 3 4]
 [6 7 8]]


In [ ]:
print(arr5.dtype)#int64 represents signed 64-bit integers

int64


In [ ]:
arr6 = np.array(['apple','banana','mango'])
print(arr6.dtype)#unicode string of length 6 characters

<U6


In [ ]:
arr7 = np.array([1,2,3,4], dtype='S')
print(arr7)#string data type
print(arr7.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr8 = np.array([1,2,3,4,5], dtype='i')
print(arr8.dtype)

int32


In [ ]:
arr9 = np.array(['a', '1', '2'], dtype='i')
print(arr9.dtype)

ValueError: ignored

In [ ]:
arr10 = np.array([3.47, 2.141, 4.95])
newarr = arr10.astype('i')
print(newarr)
print(newarr.dtype)

[3 2 4]
int32


In [ ]:
arr11 = np.array([1.1, 2.2, 3.2])
newarr = arr11.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
ar=np.array([1,2,3,4,5])
x=ar.copy()
arr[0]=42

print(ar)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
ar1=np.array([1,2,3,4,5])
y=ar1.view()
ar1[0]=45

print(ar1)
print(y)

[45  2  3  4  5]
[45  2  3  4  5]


In [ ]:
y[0] = 250
print(ar1)

[250   2   3   4   5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
# Reshaping arrays (Reshape From 1-D to 3-D)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)#2-no of elem in 1D; 3-no of elem in 2D; 2-no of elem in 3D
print(newarr)
print(newarr.ndim)
print(newarr.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [ ]:
# Flattening the arrays (Converting a multidimensional array into a 1D array)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [ ]:
# Iterating Arrays - 1D
arr = np.array([1, 2, 3])
for x in arr:
  print(x)


1
2
3


In [ ]:
#2D
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)
for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
for x in arr:
  print(x)
for x in arr:
  for y in x:
    print(y)
for x in arr:
  for y in x:
    for z in y:
      print(z)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[3 4]
[5 6]
[7 8]
1
2
3
4
5
6
7
8


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2],[6,5]])
arr2=np.array([[3,4],[8,9]])
arr=np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 3 4]
 [6 5 8 9]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr,2)
print(newarr)
print(newarr[0])
print(newarr[1])
#print(newarr[2])

[array([1, 2, 3]), array([4, 5])]
[1 2 3]
[4 5]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]


In [5]:
import numpy as np
arr = np.array([93,82,3,11])
print(np.sort(arr))

[ 3 11 82 93]


In [6]:
arr1 = np.array(['bana', 'guava','custard','xio','grape','pine'])
print(np.sort(arr1))

['bana' 'custard' 'grape' 'guava' 'pine' 'xio']


In [8]:
arr2 = np.array([[1,24,3],[46,20,1]])
print(np.sort(arr2))

[[ 1  3 24]
 [ 1 20 46]]


In [13]:
from numpy import random
x = random.randint(100)
print(x)


2


In [17]:
x1 = random.rand(20)
print(x1)

[0.80220024 0.02622903 0.65455334 0.54933134 0.33229505 0.1212073
 0.33995529 0.6280478  0.16347392 0.71912474 0.5559149  0.6594097
 0.73180391 0.32333751 0.3689879  0.72669426 0.33534389 0.79722552
 0.09006961 0.29865726]


In [18]:
x2 = random.randint(100, size=(3, 5))
x2

array([[62, 88, 81,  8, 76],
       [23, 27, 60,  1, 47],
       [46, 38, 93, 17, 47]])

In [20]:
x3 = random.rand(3,5)
print(x3)

[[0.32722485 0.76873815 0.95518534 0.73347319 0.52966428]
 [0.4371707  0.16612784 0.08877949 0.5678491  0.30795612]
 [0.10892818 0.25740354 0.18653237 0.00590279 0.17109696]]


In [21]:
a=np.array([[1,3,6],[3,4,2],[5,4,6]])
b=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(a+2)
print(b-1)
print(a*12)


[[3 5 8]
 [5 6 4]
 [7 6 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[12 36 72]
 [36 48 24]
 [60 48 72]]


In [22]:
print(a/2)
c=a+b
print(c)

[[0.5 1.5 3. ]
 [1.5 2.  1. ]
 [2.5 2.  3. ]]
[[2 4 7]
 [4 5 3]
 [6 5 7]]


In [23]:
d=a-b
print(d)


[[0 2 5]
 [2 3 1]
 [4 3 5]]


In [24]:
e=a*b
print(e)


[[1 3 6]
 [3 4 2]
 [5 4 6]]


In [25]:
#transpose
print(a)
ta=np.transpose(a)
print(ta)

[[1 3 6]
 [3 4 2]
 [5 4 6]]
[[1 3 5]
 [3 4 4]
 [6 2 6]]


In [26]:
a=np.arange(5,50,2)
a

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [27]:
print('Mean: ',np.mean(a))
print('Standard deviation: ',np.std(a))
print('Median: ',np.median(a))

Mean:  27.0
Standard deviation:  13.2664991614216
Median:  27.0


In [28]:
print('min: ',np.min(a))

min:  5


In [29]:
print('max: ',np.max(a))

max:  49


In [31]:
a=np.array([[1,3,5],[2,2,1],[4,5,3]])
print(a)
print('Min: ',np.min(a, axis=0))
print('Max: ',np.max(a, axis=1))

[[1 3 5]
 [2 2 1]
 [4 5 3]]
Min:  [1 2 1]
Max:  [5 2 5]


In [35]:
from numpy import random
x=random.choice([3,5,7,9], p=[0.1, 0.7, 0.2, 0.0], size=(100))
print(x)


[5 5 5 5 5 5 5 5 3 3 5 5 5 5 5 5 7 3 7 3 5 3 5 5 7 7 5 3 5 5 7 5 5 7 5 3 7
 7 5 7 5 5 5 3 5 5 5 5 5 5 5 5 5 7 5 5 7 7 3 5 7 5 5 5 5 5 5 7 7 5 5 5 5 5
 5 7 5 5 5 7 7 7 7 5 7 5 5 7 5 5 5 3 5 5 3 5 5 7 5 7]


In [36]:
y=random.choice([4,6,8,0],p=[0.1,0.4,0.5,0.0],size=(3,5))
print(y)

[[8 8 8 4 6]
 [8 6 8 6 8]
 [6 6 8 6 4]]


In [40]:
x=random.normal(size=(2,3))
print(x)

[[ 0.20346199  0.47807728  0.18321399]
 [-0.20773305 -0.55515705  0.4150484 ]]


In [39]:
y=random.normal(loc=1, scale=2, size=(2,3))
print(y)

[[-2.11223204 -0.26028295  3.30774098]
 [ 1.90389606  1.85973006  6.12001769]]
